#!/usr/bin/env python

try:
    from spoppy import main
except ImportError:
    import sys
    import os
    # import pdb; pdb.set_trace()
    sys.path.append(os.path.abspath('.'))
    from spoppy import main

main()
